### ISSUE TITLE
Install fails on RHEL7

### ISSUE THREAD

**Issue by chamarthy** [imp/nfstest#1]
There seems to be some issue with manpage creation during install using python. Could someone let me know what the problem could be?
# sudo python setup.py install

running install
running build
Creating man page for test/nfstest_posix
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    (os.path.join(c.NFSTEST_USRMAN, 'man1'), c.NFSTEST_MAN1),
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 34, in run
    create_manpage.run()
  File "/root/nfstest/tools/create_manpage.py", line 528, in run
    create_manpage(script, manpage)
  File "/root/nfstest/tools/create_manpage.py", line 187, in create_manpage
    version = pstdout.split()[1]
IndexError: list index out of range

**Comment by chamarthy** [comment]
Sorry.. got it fixed. Forgot to run nfstest_config.py prior.
