### ISSUE TITLE
setup error with print 

### ISSUE THREAD

**Issue by xiaoyaoyouyue** [imp/nfstest#2]
I use " python3 setup.py install" to install，the error is as follows,Have you encountered it?

root@ubt-2204:~/toolkit_ubt2204/nfstest# python3 setup.py install
Traceback (most recent call last):
  File "/root/toolkit_ubt2204/nfstest/setup.py", line 28, in <module>
    from tools import create_manpage
  File "/root/toolkit_ubt2204/nfstest/tools/create_manpage.py", line 172
    print (f"Creating man page for {src})
           ^
SyntaxError: unterminated string literal (detected at line 172)

**Comment by xiaoyaoyouyue** [comment]
I tried to modify the following code。

172 print ("Creating man page for %s" % src)

Then report the error again

![image](https://github.com/imp/nfstest/assets/76654295/b0a55bc8-c5d2-4bea-ac3b-29bed925debf)
